<#include "/WEB-INF/ftl/component/ui/text.ftl"/>
<#include "/WEB-INF/ftl/component/ui/select.ftl"/>
<#include "/WEB-INF/ftl/component/ui/radio.ftl"/>
<#include "/WEB-INF/ftl/component/ui/checkbox.ftl"/>
<#include "/WEB-INF/ftl/component/ui/checkboxlist.ftl"/>
<#include "/WEB-INF/ftl/component/ui/textarea.ftl"/>
<#include "/WEB-INF/ftl/component/ui/hidden.ftl"/>
<#include "/WEB-INF/ftl/component/ui/file.ftl"/>
<#include "/WEB-INF/ftl/component/ui/tree.ftl"/>
<#include "/WEB-INF/ftl/component/ui/table.ftl"/>
<#include "/WEB-INF/ftl/component/ui/table-column.ftl"/>
<#include "/WEB-INF/ftl/component/ui/button.ftl"/>
<#include "/WEB-INF/ftl/component/ui/password.ftl"/>
<#include "/WEB-INF/ftl/component/ui/editor.ftl"/>
<#include "/WEB-INF/ftl/component/ui/form.ftl"/>
<#include "/WEB-INF/ftl/component/ui/td.ftl"/>
<#include "/WEB-INF/ftl/component/ui/tr.ftl"/>
<#include "/WEB-INF/ftl/component/ui/self_define_widget.ftl"/>
<#include "/WEB-INF/ftl/component/ui/table_gird.ftl"/>
<#include "/WEB-INF/ftl/component/ui/table_gird_edit.ftl"/>
<#include "/WEB-INF/ftl/component/ui/datagrid.ftl"/>
<#include "/WEB-INF/ftl/component/ui/commonQueryCondition.ftl"/>
<#include "/WEB-INF/ftl/component/ui/sizetype_column.ftl"/>
<#include "/WEB-INF/ftl/component/ui/toolbar.ftl"/>
<#include "/WEB-INF/ftl/component/ui/date.ftl"/>